fillers = {
    "please", "kindly", "just", "actually", "basically", "literally",
    "seriously", "totally", "absolutely", "definitely", "certainly",
    "simply", "merely",
    "I think", "I believe", "I feel", "in my opinion", "it seems",
    "it appears", "I guess", "I suppose", "I wonder", "to be honest",
    "honestly", "frankly", "quite frankly"
}

aggressive_fillers = {
    "particularly", "especially", "specifically",
    "generally", "typically", "usually", "normally", "commonly",
    "frequently", "often", "sometimes", "occasionally", "rarely",
    "hardly", "barely", "almost", "nearly", "approximately",
    "roughly", "about", "around", "perhaps", "maybe", "possibly",
    "probably", "likely", "presumably", "supposedly", "allegedly",
}


safe_replacements = {
    "I would like to ask you to please": "Please",
    "I would like to request that you": "Please",
    "could you please help me with": "help with",
    "would you mind helping me": "help with",
    "I need assistance with": "help with",
    "in order to": "to",
    "due to the fact that": "because",
    "for the purpose of": "for",
    "with regard to": "regarding",
    "with respect to": "regarding",
    "take into consideration": "consider",
    "make a decision": "decide",
    "in the event that": "if",
    "at this point in time": "now",
    "at the present time": "now"
}


verbose_replacements = {
    "in order to": "to",
    "due to the fact that": "because",
    "at this point in time": "now",
    "for the purpose of": "for",
    "with regard to": "about",
    "in spite of the fact that": "although",
    "a large number of": "many",
    "a small number of": "few",
    "a number of": "several",
    "has the ability to": "can",
    "is able to": "can",
    "is required to": "must",
    "it is necessary to": "must",
    "in the event that": "if",
    "take into consideration": "consider",
    "give consideration to": "consider",
    "make a decision": "decide",
    "make use of": "use",
    "conduct an analysis of": "analyze",
    "provide an explanation of": "explain",
    "with the exception of": "except",
    "at this time": "now",
    "at a later date": "later",
    "the field of": "field of",
    "various different": "various",
    "the various": "various",
    "the different": "different",
    "a comprehensive": "comprehensive",
    "the comprehensive": "comprehensive",
    "utilized": "used",
    "utilizes": "uses",
    "utilizing": "using",
    "utilization": "use",
    "utilize": "use",
}


cleanup_patterns = [
    (r'\bI like to ask to me\b', ''),
    (r'\bI like to ask\b', ''),
    (r'\bto me write\b', 'write'),
    (r'\bme write\b', 'write'),
    (r'\bprovide me with\b', 'provide'),
    (r'\bwrite me\b', 'write'),
    (r'\bto you\b', ''),
    (r'\bto me\b', ''),
    (r'\bWell[, ]*', ''),
    (r'\bknow[, ]*', ''),
    (r'\bthat we should probably consider looking into the possibility of\b', 'explore'),
    (r'\bwe should probably consider\b', 'we should'),
    (r'\bconsider looking into\b', 'explore'),
    (r'\bthe possibility of\b', ''),
    (r'\bsome sort of\b', ''),
    (r'\bkind of\b', ''),
    (r'\smaybe\s', ' '),
    (r'\s+', ' '),
    (r"\bI(?:'d| would)? be (?:extremely|very|really|truly)? grateful if you could\b", ''),
    (r"\bkindly assist me\b", 'help'),
    (r"\bassist me\b", 'help'),
    (r"\bin understanding how to\b", 'explain how to'),
    (r"\bplease let me know if you need any additional information\b", ''),
    (r"\blet me know if you need any more info\b", ''),
    (r"\blet me\b", ''),
    (r"\byou could\b", ''),
    (r'\s+,', ','),
    (r'\s+\.', '.'),
    (r'\s+!', '!'),
    (r'\s+\?', '?'),
    (r'\s{2,}', ' '),
    (r'\bI hope you can help\b', 'help'),
    (r'\bthank you (so )?(much )?(for your time and consideration)?\b', ''),
    (r'\bso much for your time and consideration\b', ''),
    (r"\bI\s+hope\s+you\s+can\s+help\b[.,!]*", ""),
    (r"\bI['’]?m\s+(really|very|extremely)\s+(\w+ing|\w+)\b", r"I'm \2"),
    (r"\bI\s+would\s+greatly\s+appreciate\b[.,!]*", ""),
    (r"\bI hope you? can?\s*(help|assist)?\b", "help"),
    (r'\b(?:you\s+)?(?:see|know)\b', ''),
    (r'\b(?:you\s+)?(?:might|may)?\s*want\s*(?:to)?\s*consider\b', ''),
    (r'\b(?:you\s+)?(?:could|should)\s*consider\b', ''),
    (r'\b(?:you\s+)?(?:might|may)?\s*want\s*(?:to)?\b', ''),
    (r'\b(?:i\s+)?was\s+thinking\s+that\b', ''),
    (r'\b(?:i\s+)?was\s+wondering\s+if\b', ''),
    (r'\b(?:i\s+)?think\s+that\b', ''),
    (r'\b(?:i\s+)?believe\s+that\b', ''),
    (r'\b(?:i\s+)?feel\s+that\b', ''),
    (r'\bperhaps\b', ''),
    (r'\bpossibly\b', ''),
    (r"\b(could|would|can|will)\s+you\s+(please|kindly|possibly|maybe|briefly)?\s*(explain|tell|show|write|help|give|do)\b", r"\3"),
    (r"\b(please|kindly|maybe|possibly|briefly)\s*(just\s*)?(explain|tell|show|write|help|give|do)\b", r"\3"),
    (r"\bi\s+would\s+(really|greatly|truly)?\s*appreciate\s+it\s+if\s+you\s+could\b", ""),
    (r"\bi['’]d\s+(really|greatly|truly)?\s*appreciate\s+it\s+if\s+you\s+could\b", ""),
    (r"\bi\s+(really|greatly|truly)?\s*need\s+help\s+with\b", ""),
    (r"\bjust\s+(a\s+quick\s+)?question\b", ""),
    (r"\bI\s+(just|only)\s+wanted\s+to\s+ask\b", ""),
    (r"\bto\s+ask\s+you\b", ""),
    (r"\bif\s+(you\s+)?don['’]t\s+mind\b", ""),
    (r"\bthis\s+may\s+be\s+a\s+stupid\s+question\s+but\b", ""),
    (r"\b(?:I['’]?m|I am)\s+(new|noob|beginner|not\s+an\s+expert)\b", ""),
    (r"\b(?:sorry\s+(if|for)|apologies\s+(if|for))\b.*?[,\.]", ""),
    (r"\b(?:I\s+was\s+)?(?:wondering|thinking)\s+(if|whether)\b", ""),
    (r"\b(?:would\s+it\s+be\s+possible\s+to|is\s+it\s+okay\s+if\s+you)\b", ""),
    (r"\b(?:I\s+was\s+hoping\s+you\s+could)\b", ""),
    (r"\b(?:Let\s+me\s+know\s+if\s+you\s+need\s+(any\s+)?(more|additional)\s+(info(?:rmation)?|details))\b", ""),
    (r"\b(so|well|okay|anyway)[,\.]?\s*", ""),
    (r"\b(I\s+would\s+like\s+(to\s+)?(request|ask)|I\s+want\s+(to\s+)?(request|ask))\s+that\s+you\b", "")
]


pre_patterns = [
    r"\bI would like to kindly ask you to please\b",
    r"\bI would like to ask you to please\b",
    r"\bI would like to ask you to\b",
    r"\bI would like to ask\b",
    r"\bI want to ask you to\b",
    r"\bI want to ask\b",
    r"\bCan you please\b",
    r"\bCould you please\b",
    r"\bWould you please\b",
    r"\bPlease help me\b",
    r"\bI need you to help me\b",
    r"\bI need help with\b",
]


redundant_patterns = [
    (r'\b(?:can|will|could|would|should|must)\s+you\s+(help|show|tell|explain|write|create|make|provide|give)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\byou\s+(?:need to|have to|are going to|are able to|are supposed to)\s+(help|show|tell|explain|write|create|make|provide|give)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\byou\s+are\s+capable\s+of\s+(helping|showing|telling|explaining|writing|creating|making|providing|giving)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\b(help|show|tell|teach|explain|describe|write|send|give|provide)\s+(?:me|to me)\b(?!\s+(?:to|with|how|what|where|about|understand|figure))', r'\1'),
    (r'\bI\s+(?:want|need|would like|require|ask|request)\s+(?:you\s+)?to\s+(?!\s+(?:know|understand|see|remember))', ''),
    (r'\bplease\s+(help|show|tell|explain|write|create|make|provide|give)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\bI\s+need\s+(?:help|assistance|support)\b(?!\s+(?:with|to|understanding))', 'help'),
    (r'\bI\s+need\s+you\b(?!\s+(?:to|for|with))', ''),
    (r'\b(?:do|did|will|would)\s+you\b(?=\s+(?:have|know|think|understand|see|want|need|like))', ''),
    (r'\byou\s+(?:can\s+|will\s+|should\s+|must\s+|need to\s+|have to\s+)?do\s+this\b(?!\s+(?:by|with|for|to|when|where))', 'do this'),
]

greetings = {
    "hello", "hi", "hey", "greetings", "good morning", "good afternoon",
    "good evening", "dear", "to whom it may concern", "hi there",
    "hello there", "hey there", "good day", "howdy", "yo", "sup",
    "hiya", "g'day", "morning", "afternoon", "evening", "salutations",
    "welcome", "dearest", "how are you", "how are you doing",
    "what's up", "wassup", "how's it going", "hey folks", "hi folks"
}


request_patterns = [
    (r'\b(?:please\s+)?(help|assist|aid|support|explain|clarify|provide|give|show|demonstrate)\b', r'\1'),
    (r'\b(?:i would like|i want|i need|could you|can you|would you|please)\s+(?:to\s+)?(help|assist|aid|support|explain|clarify|provide|give|show|demonstrate)\b', r'\1'),
    (r'\b(?:could you help me with|can you help me with|would you help me with|please help me with|help me with|i need help with|i need you to help me with)\b', 'help with'),
    (r'\b(?:i would like to ask you to please|i would like to ask you to|i would like to ask|i want to ask you to|i want to ask|i am asking you to|i am requesting|i request that you|please)\b', ''),
    (r'\b(?:if you could|if you would|if possible|would you mind|would you kindly|could you please)\b', ''),
    (r'\b(?:thank you|thanks|much appreciated|many thanks|thanks a lot|thank you very much)\b', ''),
    (r'\bI\s+was\s+wondering\s*(?:if|whether)?\s*', ''),
    (r'\b(?:I\s+am|I\'m)\s+looking\s+(?:for|to)\s*', ''),
    (r'\b(?:I\s+would\s+like|I\'d\s+like)\s+to\s+(?:know|find\s+out|understand)\b\s*', ''),
    (r'\b(?:my|the)\s+question(?:\s+I\s+have)?\s+is\s*', ''),
    (r'\b(?:Can|Could|Would)\s+you\s+(?:tell\s+me|explain|show\s+me|provide\s+me\s+with)\b\s*', ''),
    (r'\b(?:I\s+am|I\'m)\s+(?:writing|contacting)\s+(?:you\s+)?to\s*', ''),
    (r'\b(?:I\s+need|I\s+want)\s+you\s+to\s*', ''),
    (r'\b(?:I\s+am|I\'m)\s+trying\s+to\s*', ''),

]

greeting_patterns = [
    r'^to\s+whom\s+it\s+may\s+concern[.!]?\s*',
    r'^good\s+(morning|afternoon|evening|day)[.!]?\s*',
    r'^dear\s+.*?,?\s*',
    r'\bhello there[.!]?\s*',
    r'\bhi there[.!]?\s*',
    r'\bhey there[.!]?\s*',
    r'\bhow are you( doing)?[.!]?\s*',
    r'\bwhat\'?s up[.!]?\s*',
    r'\bhey folks[.!]?\s*',
    r'\bhi folks[.!]?\s*',
    r'\bwelcome[.!]?\s*',
    r'\bsalutations[.!]?\s*',
    r'^hello[.!]?\s*',
    r'^hi[.!]?\s*',
    r'^hey[.!]?\s*',
    r'^howdy[.!]?\s*',
    r'^hiya[.!]?\s*',
    r'^g\'day[.!]?\s*',
    r'^yo[.!]?\s*',
    r'^sup[.!]?\s*',
]

chatbot_optimizations = {
    "contractions": {
        "do not": "don't", "does not": "doesn't", "did not": "didn't",
        "will not": "won't", "would not": "wouldn't", "could not": "couldn't",
        "should not": "shouldn't", "cannot": "can't", "can not": "can't",
        "are not": "aren't", "is not": "isn't", "was not": "wasn't",
        "were not": "weren't", "have not": "haven't", "has not": "hasn't",
        "had not": "hadn't", "I am": "I'm", "you are": "you're", "he is": "he's",
        "she is": "she's", "it is": "it's", "we are": "we're", "they are": "they're",
        "I will": "I'll", "you will": "you'll", "he will": "he'll", "she will": "she'll",
        "it will": "it'll", "we will": "we'll", "they will": "they'll",
        "I would": "I'd", "you would": "you'd", "he would": "he'd", "she would": "she'd",
        "we would": "we'd", "they would": "they'd", "I have": "I've", "you have": "you've",
        "we have": "we've", "they have": "they've", "let us": "let's", "cannot": "can't",
        "would have": "would've", "could have": "could've", "should have": "should've",
        "they will": "they'll", "we will": "we'll"
    },
    "preposition_simplifications": {
        "in order to": "to", "due to the fact that": "because", "for the purpose of": "for",
        "with regard to": "about", "with respect to": "about", "in relation to": "about",
        "in reference to": "about", "as a result of": "because", "on account of": "because",
        "in spite of": "despite", "by means of": "by", "for the reason that": "because",
        "in view of": "because", "prior to": "before", "subsequent to": "after",
        "in the event that": "if", "in case": "if", "at the time when": "when",
        "during the time that": "while", "at this moment in time": "now", "at this point": "now",
        "in the course of": "during", "in the process of": "during", "for the sake of": "for",
        "with the exception of": "except",
    },
    "redundant_phrases": {
        "and also": "and", "but also": "but", "also too": "also", "but however": "but",
        "and additionally": "and", "so therefore": "so", "thus therefore": "thus",
        "each and every": "each", "any and all": "all", "first and foremost": "first",
        "null and void": "void", "basic fundamentals": "basics", "general consensus": "consensus",
        "final outcome": "outcome", "end result": "result", "past history": "history",
        "future plans": "plans", "advance warning": "warning", "brief summary": "summary",
        "close proximity": "proximity", "exact same": "same", "completely finished": "finished",
        "totally destroyed": "destroyed", "absolutely perfect": "perfect", "very unique": "unique",
        "most important": "important", "more better": "better", "most favorite": "favorite",
        "advance planning": "planning", "end result": "result", "past experience": "experience",
        "future outlook": "outlook", "unexpected surprise": "surprise", "free gift": "gift",
        "true facts": "facts", "new innovation": "innovation", "close scrutiny": "scrutiny",
    },
    "intensifier_reductions": {
        "very very": "very", "really really": "really", "quite quite": "quite",
        "extremely very": "extremely", "really very": "very", "quite very": "very",
        "pretty much": "mostly", "kind of": "somewhat", "sort of": "somewhat",
        "more or less": "roughly", "a bit": "slightly", "a little": "slightly",
        "a lot": "much", "a great deal": "much", "a large amount": "much",
        "a significant amount": "much", "super very": "very", "totally completely": "totally",
        "absolutely completely": "absolutely", "really quite": "really", "really extremely": "really",
        "very much": "much", "really really": "really", "absolutely completely": "absolutely",
        "quite a bit": "somewhat", "totally absolutely": "totally",
    },
    "removable_articles": ["a", "an", "the"],
    "conjunction_simplifications": {
        "as well as": "and", "along with": "and", "in addition to": "and",
        "together with": "and", "not only but also": "and", "both and": "and",
        "either or": "or", "whether or not": "whether", "if and when": "when",
        "when and if": "when"
    },
    "question_simplifications": {
        "I was wondering if": "Is", "I would like to know": "What", "Could you tell me": "What",
        "Can you explain": "Explain", "Would you mind telling me": "What", "I'm curious about": "What about",
        "Do you happen to know": "Do you know", "Would it be possible to": "Can you",
        "I was hoping you could": "Can you", "Is there a way to": "How to"
    },
    "transition_simplifications": {
        "as a matter of fact": "actually", "to tell the truth": "honestly", "believe it or not": "surprisingly",
        "as you can see": "clearly", "it goes without saying": "obviously", "needless to say": "obviously",
        "in other words": "meaning", "that is to say": "meaning", "to put it simply": "simply",
        "to sum up": "overall", "in conclusion": "finally", "in summary": "overall",
        "all things considered": "overall", "on the whole": "overall", "by and large": "generally",
        "for the most part": "mostly", "more often than not": "usually"
    },
    "aggressive_fillers": [
        fillers, aggressive_fillers
    ],
    "courtesy_removals": [
        "please", "thank you", "thanks", "you're welcome", "excuse me",
        "pardon me", "sorry", "I apologize", "my apologies", "if you don't mind",
        "if it's not too much trouble", "I hope you don't mind", "I appreciate it",
        "I'm grateful", "that would be great", "that sounds good", "perfect",
        "wonderful", "excellent", "fantastic", "amazing", "awesome", "cheers",
        "many thanks", "much appreciated", "no worries", "gladly", "you're so kind",
        "many thanks in advance", "thank you kindly", "much obliged", "looking forward to your response",
        "appreciate your help", "thanks a lot", "thanks so much", "greatly appreciate", "hope to hear from you soon",
    ],
    "chatbot_patterns": [
        (r'\b(?:I think|I believe|I feel|I guess|I suppose|it seems|it appears|I wonder|to be honest|honestly|frankly|quite frankly)\s+(?:that\s+)?', ''),
        (r'\b(?:maybe|perhaps|possibly|probably|likely|presumably|supposedly|allegedly|reportedly|apparently)\s+', ''),
        (r'\bif it is possible\b', 'if possible'),
        (r'\bwhen it is\b', 'when'),
        (r'\bwhere it is\b', 'where'),
        (r'\bit is (?:important|necessary|essential|crucial|vital) (?:that|to)\s+', ''),
        (r'\bthere (?:is|are) (?:a|an|the)?\s*', ''),
        (r'\bat this point in time\b', 'now'),
        (r'\bat the present time\b', 'now'),
        (r'\bat the current time\b', 'now'),
        (r'\bin the near future\b', 'soon'),
        (r'\bin the not too distant future\b', 'soon'),
        (r'\bas (?:you can see|mentioned|stated|noted|discussed)\s*,?\s*', ''),
        (r'\bas (?:I|we) (?:said|mentioned|stated|noted|discussed)\s*,?\s*', ''),
        (r'\bvery (?:very|much|greatly|highly|extremely|incredibly|absolutely)\b', 'very'),
        (r'\bextremely (?:very|much|greatly|highly|incredibly|absolutely)\b', 'extremely'),
        (r'\b(?:I think|I believe|I feel|I guess|I suppose|it seems|it appears|I wonder|to be honest|honestly|frankly|quite frankly|in my opinion|as far as I know)\s+(?:that\s+)?', ''),
        (r'\bjust\s+(to)?\s*say\b', ''),
        (r'\bI would like to (?:ask|request|know|find out)\b', ''),
        (r'\bI am writing to\b', ''),
        (r'\bplease be informed that\b', ''),
        (r'\bI am contacting you to\b', ''),
        (r'\bthis is to\b', ''),
        (r'\bdo you happen to\b', ''),
        (r'\bI (?:would|want to|like to|am hoping to|am writing to|am contacting you to) (?:ask|request|know|find out|inform you|notify you|tell you)\b', ''),
        (r'\bplease (?:kindly )?(?:let me know|inform me|provide me|send me)\b', ''),
        (r'\bI am (?:just|simply) writing\b', ''),
        (r'\bI (?:was|am) wondering if\b', ''),
        (r'\bthank you (?:for your time and consideration|so much|very much|in advance)\b', ''),
        (r'\bI would appreciate it if you could\b', ''),
    ]
}