fillers = {
    "please", "kindly", "just", "actually", "basically", "literally",
    "seriously", "totally", "absolutely", "definitely", "certainly",
    "simply", "merely", "particularly", "especially", "specifically",
    "generally", "typically", "usually", "normally", "commonly",
    "frequently", "often", "sometimes", "occasionally", "rarely",
    "hardly", "barely", "almost", "nearly", "approximately",
    "roughly", "about", "around", "perhaps", "maybe", "possibly",
    "probably", "likely", "presumably", "supposedly", "allegedly",
    "I think", "I believe", "I feel", "in my opinion", "it seems",
    "it appears", "I guess", "I suppose", "I wonder", "to be honest",
    "honestly", "frankly", "quite frankly"
}
safe_replacements = {
            "I would like to ask you to please": "Please",
            "I would like to request that you": "Please",
            "could you please help me with": "help me",
            "would you mind helping me": "help me",
            "I need assistance with": "help with",
            "in order to": "to",
            "due to the fact that": "because",
            "for the purpose of": "for",
            "with regard to": "regarding",
            "with respect to": "regarding",
            "take into consideration": "consider",
            "make a decision": "decide",
            "in the event that": "if",
            "at this point in time": "now",
            "at the present time": "now"
        }
verbose_replacements = {
            "in order to": "to",
            "due to the fact that": "because",
            "at this point in time": "now",
            "for the purpose of": "for",
            "with regard to": "about",
            "in spite of the fact that": "although",
            "a large number of": "many",
            "a small number of": "few",
            "a number of": "several",
            "has the ability to": "can",
            "is able to": "can",
            "is required to": "must",
            "it is necessary to": "must",
            "in the event that": "if",
            "take into consideration": "consider",
            "give consideration to": "consider",
            "make a decision": "decide",
            "make use of": "use",
            "conduct an analysis of": "analyze",
            "provide an explanation of": "explain",
            "with the exception of": "except",
            "at this time": "now",
            "at a later date": "later",
            "the field of": "",
            "various different": "various",
            "the various": "various",
            "the different": "different",
            "a comprehensive": "comprehensive",
            "the comprehensive": "comprehensive",
            "utilized": "used",
            "utilizes": "uses",
            "utilizing": "using",
            "utilization": "use",
            "utilize": "use",
        }

cleanup_patterns = [
    (r'\bI like to ask to me\b', ''),
    (r'\bI like to ask\b', ''),
    (r'\bto me write\b', 'write'),
    (r'\bme write\b', 'write'),
    (r'\bhelp me\b', 'help'),
    (r'\bprovide me with\b', 'provide'),
    (r'\bwrite me\b', 'write'),
    (r'\bto you\b', ''),
    (r'\bto me\b', ''),
    (r'\bWell[, ]*', ''),
    (r'\bknow[, ]*', ''),
    (r'\bthat we should probably consider looking into the possibility of\b', 'explore'),
    (r'\bwe should probably consider\b', 'we should'),
    (r'\bconsider looking into\b', 'explore'),
    (r'\bthe possibility of\b', ''),
    (r'\bsome sort of\b', ''),
    (r'\bkind of\b', ''),
    (r'\smaybe\s', ' '),
    (r'\s+', ' '),
    (r"\bI(?:'d| would)? be (?:extremely|very|really|truly)? grateful if you could\b", ''),
    (r"\bkindly assist me\b", 'help'),
    (r"\bassist me\b", 'help'),
    (r"\bin understanding how to\b", 'explain how to'),
    (r"\bplease let me know if you need any additional information\b", ''),
    (r"\blet me know if you need any more info\b", ''),
    (r"\blet me\b", ''),
    (r"\byou could\b", ''),
    (r'\s+,', ','),
    (r'\s+\.', '.'),
    (r'\s+!', '!'),
    (r'\s+\?', '?'),
    (r'\s{2,}', ' '),
    (r'\bI hope you can help\b', 'help'),
    (r'\bthank you (so )?(much )?(for your time and consideration)?\b', ''),
    (r'\bso much for your time and consideration\b', ''),
    (r"\bI\s+hope\s+you\s+can\s+help\b[.,!]*", ""),
    (r"\bI['’]?m\s+(really|very|extremely)\s+(\w+ing|\w+)\b", r"I'm \2"),
    (r"\bI\s+would\s+greatly\s+appreciate\b[.,!]*", ""),
    (r"\bI hope you? can?\s*(help|assist)?\b", "help"),
    (r"\bI(?:'m| am)\s+\w+\s+(?:this|it|with|about|for|to|on|in|at|of|from|by|as)\b", ''),
    (r'\b(?:and|or|but|so|if|because|though|although|while|whereas|since|after|before|once)\b', ''),
    (r'\b(this|it|and|if|to|me|my|so|as|at|on|in|by|of|or|up|be|do|go|we|us|am)\b', ''),
    (r'\s{2,}', ' '),
    (r'\b(?:you\s+)?(?:see|know)\b', ''),
    (r'\b(?:you\s+)?(?:might|may)?\s*want\s*(?:to)?\s*consider\b', ''),
    (r'\b(?:you\s+)?(?:could|should)\s*consider\b', ''),
    (r'\b(?:you\s+)?(?:might|may)?\s*want\s*(?:to)?\b', ''),
    (r'\b(?:i\s+)?was\s+thinking\s+that\b', ''),
    (r'\b(?:i\s+)?was\s+wondering\s+if\b', ''),
    (r'\b(?:i\s+)?think\s+that\b', ''),
    (r'\b(?:i\s+)?believe\s+that\b', ''),
    (r'\b(?:i\s+)?feel\s+that\b', ''),
    (r'\bperhaps\b', ''),
    (r'\bmaybe\b', ''),
    (r'\bpossibly\b', ''),
]

pre_patterns = [
            r"\bI would like to kindly ask you to please\b",
            r"\bI would like to ask you to please\b",
            r"\bI would like to ask you to\b",
            r"\bI would like to ask\b",
            r"\bI want to ask you to\b",
            r"\bI want to ask\b",
            r"\bCan you please\b",
            r"\bCould you please\b",
            r"\bWould you please\b",
            r"\bPlease help me\b",
            r"\bI need you to help me\b",
            r"\bI need help with\b",
        ]

redundant_patterns = [
            (r'\byou help me\b', 'help'),
            (r'\byou do this\b', 'do this'),
            (r'\byou can help\b', 'help'),
            (r'\byou should\b', 'should'),
            (r'\byou need to\b', 'need to'),
            (r'\byou must\b', 'must'),
            (r'\bhelp me\b', 'help'),
            (r'\bshow me\b', 'show'),
            (r'\btell me\b', 'tell'),
            (r'\bI want you to\b', ''),
            (r'\bI need you to\b', ''),
            (r'\bcan you\b', 'can'),
            (r'\bwill you\b', 'will'),
            (r"\b(help|assist|support) me\b", ""),
            (r"\b(can|could|would|will) you (please )?(help|assist)\b", ""),
            (r"\bI (need|want|would like) you to (help|assist)\b", ""),
            (r"\bplease (help|assist)\b", ""),
            (r"\bI need help\b", ""),
            (r"\bto me\b", ""),
            (r"\bme to\b", ""),
        ]

greetings = {
    "hello", "hi", "hey", "greetings", "good morning", "good afternoon",
    "good evening", "dear", "to whom it may concern", "hi there",
    "hello there", "hey there", "good day", "howdy", "yo", "sup",
    "hiya", "g'day", "morning", "afternoon", "evening", "salutations",
    "welcome", "dearest", "how are you", "how are you doing",
    "what's up", "wassup", "how's it going", "hey folks", "hi folks"
}

request_patterns = [
    r'\b(?:i would like to ask you to please|i would like to ask you to|i would like to ask|i want to ask you to|i want to ask|please help me with|help me with|can you help me with|could you help me with|would you help me with|i need help with|i need you to help me with)\b',
    r'\b(?:i would like|i want|i need|could you|can you|would you|please)\s+(?:to\s+)?(?:help|assist|aid|support|explain|clarify|provide|give|show|demonstrate)\b',
    r'\b(?:i am asking you to|i am requesting|i request that you|please)\b',
    r'\b(?:if you could|if you would|if possible|would you mind|would you kindly|could you please)\b',
    r'\b(?:thank you|thanks|much appreciated|many thanks|thanks a lot|thank you very much)\b'
]

greeting_patterns = [
    r'^hello[.!]?\s*', r'^hi[.!]?\s*', r'^hey[.!]?\s*', r'^greetings[.!]?\s*',
    r'^good\s+(morning|afternoon|evening|day)[.!]?\s*', r'^dear\s+.*?,?\s*',
    r'^to\s+whom\s+it\s+may\s+concern[.!]?\s*', r'^howdy[.!]?\s*',
    r'^yo[.!]?\s*', r'^sup[.!]?\s*', r'^hiya[.!]?\s*', r'^g\'day[.!]?\s*',
    r'\bhello there[.!]?\s*', r'\bhi there[.!]?\s*', r'\bhey there[.!]?\s*',
    r'\bhow are you( doing)?[.!]?\s*', r'\bwhat\'?s up[.!]?\s*', r'\bhey folks[.!]?\s*',
    r'\bhi folks[.!]?\s*', r'\bwelcome[.!]?\s*', r'\bsalutations[.!]?\s*'
]

# chatbot

chatbot_optimizations = {
    "contractions": {
        "do not": "don't",
        "does not": "doesn't",
        "did not": "didn't",
        "will not": "won't",
        "would not": "wouldn't",
        "could not": "couldn't",
        "should not": "shouldn't",
        "cannot": "can't",
        "can not": "can't",
        "are not": "aren't",
        "is not": "isn't",
        "was not": "wasn't",
        "were not": "weren't",
        "have not": "haven't",
        "has not": "hasn't",
        "had not": "hadn't",
        "I am": "I'm",
        "you are": "you're",
        "he is": "he's",
        "she is": "she's",
        "it is": "it's",
        "we are": "we're",
        "they are": "they're",
        "I will": "I'll",
        "you will": "you'll",
        "he will": "he'll",
        "she will": "she'll",
        "it will": "it'll",
        "we will": "we'll",
        "they will": "they'll",
        "I would": "I'd",
        "you would": "you'd",
        "he would": "he'd",
        "she would": "she'd",
        "we would": "we'd",
        "they would": "they'd",
        "I have": "I've",
        "you have": "you've",
        "we have": "we've",
        "they have": "they've"
    },

    "preposition_simplifications": {
        "in order to": "to",
        "due to the fact that": "because",
        "for the purpose of": "for",
        "with regard to": "about",
        "with respect to": "about",
        "in relation to": "about",
        "in reference to": "about",
        "as a result of": "because",
        "on account of": "because",
        "in spite of": "despite",
        "by means of": "by",
        "for the reason that": "because",
        "in view of": "because",
        "prior to": "before",
        "subsequent to": "after",
        "in the event that": "if",
        "in case": "if",
        "at the time when": "when",
        "during the time that": "while"
    },

    "redundant_phrases": {
        "and also": "and",
        "but also": "but",
        "also too": "also",
        "but however": "but",
        "and additionally": "and",
        "so therefore": "so",
        "thus therefore": "thus",
        "each and every": "each",
        "any and all": "all",
        "first and foremost": "first",
        "null and void": "void",
        "basic fundamentals": "basics",
        "general consensus": "consensus",
        "final outcome": "outcome",
        "end result": "result",
        "past history": "history",
        "future plans": "plans",
        "advance warning": "warning",
        "brief summary": "summary",
        "close proximity": "proximity",
        "exact same": "same",
        "completely finished": "finished",
        "totally destroyed": "destroyed",
        "absolutely perfect": "perfect",
        "very unique": "unique",
        "most important": "important",
        "more better": "better",
        "most favorite": "favorite"
    },

    "intensifier_reductions": {
    "very very": "very",
    "really really": "really",
    "quite quite": "quite",
    "extremely very": "extremely",
    "really very": "very",
    "quite very": "very",
    "pretty much": "mostly",
    "kind of": "somewhat",
    "sort of": "somewhat",
    "more or less": "roughly",
    "a bit": "slightly",
    "a little": "slightly",
    "a lot": "much",
    "a great deal": "much",
    "a large amount": "much",
    "a significant amount": "much",
    "super very": "very",
    "totally completely": "totally",
    "absolutely completely": "absolutely",
    "really quite": "really",
    "really extremely": "really"
},

    "removable_articles": ["a", "an", "the"],

    "conjunction_simplifications": {
        "as well as": "and",
        "along with": "and",
        "in addition to": "and",
        "together with": "and",
        "not only but also": "and",
        "both and": "and",
        "either or": "or",
        "whether or not": "whether",
        "if and when": "when",
        "when and if": "when"
    },

    "question_simplifications": {
        "I was wondering if": "Is",
        "I would like to know": "What",
        "Could you tell me": "What",
        "Can you explain": "Explain",
        "Would you mind telling me": "What",
        "I'm curious about": "What about",
        "Do you happen to know": "Do you know",
        "Would it be possible to": "Can you",
        "I was hoping you could": "Can you",
        "Is there a way to": "How to"
    },

    "transition_simplifications": {
        "as a matter of fact": "actually",
        "to tell the truth": "honestly",
        "believe it or not": "surprisingly",
        "as you can see": "clearly",
        "it goes without saying": "obviously",
        "needless to say": "obviously",
        "in other words": "meaning",
        "that is to say": "meaning",
        "to put it simply": "simply",
        "to sum up": "overall",
        "in conclusion": "finally",
        "in summary": "overall",
        "all things considered": "overall",
        "on the whole": "overall",
        "by and large": "generally",
        "for the most part": "mostly",
        "more often than not": "usually"
    },

    "aggressive_fillers": [
        "actually", "basically", "literally", "honestly", "obviously",
        "seriously", "totally", "absolutely", "definitely", "certainly",
        "clearly", "surely", "indeed", "truly", "really", "quite",
        "rather", "somewhat", "fairly", "pretty", "just", "only",
        "simply", "merely", "particularly", "especially", "specifically",
        "generally", "typically", "usually", "normally", "commonly",
        "frequently", "often", "sometimes", "occasionally", "rarely",
        "hardly", "barely", "almost", "nearly", "approximately",
        "roughly", "about", "around", "perhaps", "maybe", "possibly",
        "probably", "likely", "presumably", "supposedly", "allegedly"
    ],

    "courtesy_removals": [
    "please", "thank you", "thanks", "you're welcome", "excuse me",
    "pardon me", "sorry", "I apologize", "my apologies", "if you don't mind",
    "if it's not too much trouble", "I hope you don't mind", "I appreciate it",
    "I'm grateful", "that would be great", "that sounds good", "perfect",
    "wonderful", "excellent", "fantastic", "amazing", "awesome", "cheers",
    "many thanks", "much appreciated", "no worries", "gladly", "you're so kind"
]
}

chatbot_patterns = [
    (r'\b(?:I think|I believe|I feel|I guess|I suppose|it seems|it appears|I wonder|to be honest|honestly|frankly|quite frankly)\s+(?:that\s+)?', ''),
    (r'\b(?:maybe|perhaps|possibly|probably|likely|presumably|supposedly|allegedly|reportedly|apparently)\s+', ''),
    (r'\bif it is possible\b', 'if possible'),
    (r'\bwhen it is\b', 'when'),
    (r'\bwhere it is\b', 'where'),
    (r'\bit is (?:important|necessary|essential|crucial|vital) (?:that|to)\s+', ''),
    (r'\bthere (?:is|are) (?:a|an|the)?\s*', ''),
    (r'\bat this point in time\b', 'now'),
    (r'\bat the present time\b', 'now'),
    (r'\bat the current time\b', 'now'),
    (r'\bin the near future\b', 'soon'),
    (r'\bin the not too distant future\b', 'soon'),
    (r'\bas (?:you can see|mentioned|stated|noted|discussed)\s*,?\s*', ''),
    (r'\bas (?:I|we) (?:said|mentioned|stated|noted|discussed)\s*,?\s*', ''),
    (r'\bvery (?:very|much|greatly|highly|extremely|incredibly|absolutely)\b', 'very'),
    (r'\bextremely (?:very|much|greatly|highly|incredibly|absolutely)\b', 'extremely'),
]