fillers = {
    "please", "kindly", "just", "actually", "basically", "literally",
    "seriously", "totally", "absolutely", "definitely", "certainly",
    "simply", "merely",
    "I think", "I believe", "I feel", "in my opinion", "it seems",
    "it appears", "I guess", "I suppose", "I wonder", "to be honest",
    "honestly", "frankly", "quite frankly"
}

aggressive_fillers = {
    "particularly", "especially", "specifically",
    "generally", "typically", "usually", "normally", "commonly",
    "frequently", "often", "sometimes", "occasionally", "rarely",
    "hardly", "barely", "almost", "nearly", "approximately",
    "roughly", "about", "around", "perhaps", "maybe", "possibly",
    "probably", "likely", "presumably", "supposedly", "allegedly",
}


safe_replacements = {
    "I would like to ask you to please": "Please",
    "I would like to request that you": "Please",
    "could you please help me with": "help with",
    "would you mind helping me": "help with",
    "I need assistance with": "help with",
    "in order to": "to",
    "due to the fact that": "because",
    "for the purpose of": "for",
    "with regard to": "regarding",
    "with respect to": "regarding",
    "take into consideration": "consider",
    "make a decision": "decide",
    "in the event that": "if",
    "at this point in time": "now",
    "at the present time": "now"
}


verbose_replacements = {
    "in order to": "to",
    "due to the fact that": "because",
    "at this point in time": "now",
    "for the purpose of": "for",
    "with regard to": "about",
    "in spite of the fact that": "although",
    "a large number of": "many",
    "a small number of": "few",
    "a number of": "several",
    "has the ability to": "can",
    "is able to": "can",
    "is required to": "must",
    "it is necessary to": "must",
    "in the event that": "if",
    "take into consideration": "consider",
    "give consideration to": "consider",
    "make a decision": "decide",
    "make use of": "use",
    "conduct an analysis of": "analyze",
    "provide an explanation of": "explain",
    "with the exception of": "except",
    "at this time": "now",
    "at a later date": "later",
    "the field of": "field of",
    "various different": "various",
    "the various": "various",
    "the different": "different",
    "a comprehensive": "comprehensive",
    "the comprehensive": "comprehensive",
    "utilized": "used",
    "utilizes": "uses",
    "utilizing": "using",
    "utilization": "use",
    "utilize": "use",
}


cleanup_patterns = [
    (r'\bI like to ask to me\b', ''),
    (r'\bI like to ask\b', ''),
    (r'\bto me write\b', 'write'),
    (r'\bme write\b', 'write'),
    (r'\bprovide me with\b', 'provide'),
    (r'\bwrite me\b', 'write'),
    (r'\bto you\b', ''),
    (r'\bto me\b', ''),
    (r'\bWell[, ]*', ''),
    (r'\bknow[, ]*', ''),
    (r'\bthat we should probably consider looking into the possibility of\b', 'explore'),
    (r'\bwe should probably consider\b', 'we should'),
    (r'\bconsider looking into\b', 'explore'),
    (r'\bthe possibility of\b', ''),
    (r'\bsome sort of\b', ''),
    (r'\bkind of\b', ''),
    (r'\smaybe\s', ' '),
    (r'\s+', ' '),
    (r"\bI(?:'d| would)? be (?:extremely|very|really|truly)? grateful if you could\b", ''),
    (r"\bkindly assist me\b", 'help'),
    (r"\bassist me\b", 'help'),
    (r"\bin understanding how to\b", 'explain how to'),
    (r"\bplease let me know if you need any additional information\b", ''),
    (r"\blet me know if you need any more info\b", ''),
    (r"\blet me\b", ''),
    (r"\byou could\b", ''),
    (r'\s+,', ','),
    (r'\s+\.', '.'),
    (r'\s+!', '!'),
    (r'\s+\?', '?'),
    (r'\s{2,}', ' '),
    (r'\bI hope you can help\b', 'help'),
    (r'\bthank you (so )?(much )?(for your time and consideration)?\b', ''),
    (r'\bso much for your time and consideration\b', ''),
    (r"\bI\s+hope\s+you\s+can\s+help\b[.,!]*", ""),
    (r"\bI['’]?m\s+(really|very|extremely)\s+(\w+ing|\w+)\b", r"I'm \2"),
    (r"\bI\s+would\s+greatly\s+appreciate\b[.,!]*", ""),
    (r"\bI hope you? can?\s*(help|assist)?\b", "help"),
    (r'\b(?:you\s+)?(?:see|know)\b', ''),
    (r'\b(?:you\s+)?(?:might|may)?\s*want\s*(?:to)?\s*consider\b', ''),
    (r'\b(?:you\s+)?(?:could|should)\s*consider\b', ''),
    (r'\b(?:you\s+)?(?:might|may)?\s*want\s*(?:to)?\b', ''),
    (r'\b(?:i\s+)?was\s+thinking\s+that\b', ''),
    (r'\b(?:i\s+)?was\s+wondering\s+if\b', ''),
    (r'\b(?:i\s+)?think\s+that\b', ''),
    (r'\b(?:i\s+)?believe\s+that\b', ''),
    (r'\b(?:i\s+)?feel\s+that\b', ''),
    (r'\bperhaps\b', ''),
    (r'\bpossibly\b', ''),
    (r"\b(could|would|can|will)\s+you\s+(please|kindly|possibly|maybe|briefly)?\s*(explain|tell|show|write|help|give|do)\b", r"\3"),
    (r"\b(please|kindly|maybe|possibly|briefly)\s*(just\s*)?(explain|tell|show|write|help|give|do)\b", r"\3"),
    (r"\bi\s+would\s+(really|greatly|truly)?\s*appreciate\s+it\s+if\s+you\s+could\b", ""),
    (r"\bi['’]d\s+(really|greatly|truly)?\s*appreciate\s+it\s+if\s+you\s+could\b", ""),
    (r"\bi\s+(really|greatly|truly)?\s*need\s+help\s+with\b", ""),
    (r"\bjust\s+(a\s+quick\s+)?question\b", ""),
    (r"\bI\s+(just|only)\s+wanted\s+to\s+ask\b", ""),
    (r"\bto\s+ask\s+you\b", ""),
    (r"\bif\s+(you\s+)?don['’]t\s+mind\b", ""),
    (r"\bthis\s+may\s+be\s+a\s+stupid\s+question\s+but\b", ""),
    (r"\b(?:I['’]?m|I am)\s+(new|noob|beginner|not\s+an\s+expert)\b", ""),
    (r"\b(?:sorry\s+(if|for)|apologies\s+(if|for))\b.*?[,\.]", ""),
    (r"\b(?:I\s+was\s+)?(?:wondering|thinking)\s+(if|whether)\b", ""),
    (r"\b(?:would\s+it\s+be\s+possible\s+to|is\s+it\s+okay\s+if\s+you)\b", ""),
    (r"\b(?:I\s+was\s+hoping\s+you\s+could)\b", ""),
    (r"\b(?:Let\s+me\s+know\s+if\s+you\s+need\s+(any\s+)?(more|additional)\s+(info(?:rmation)?|details))\b", ""),
    (r"\b(so|well|okay|anyway)[,\.]?\s*", ""),
    (r"\b(I\s+would\s+like\s+(to\s+)?(request|ask)|I\s+want\s+(to\s+)?(request|ask))\s+that\s+you\b", "")
]


pre_patterns = [
    r"\bI would like to kindly ask you to please\b",
    r"\bI would like to ask you to please\b",
    r"\bI would like to ask you to\b",
    r"\bI would like to ask\b",
    r"\bI want to ask you to\b",
    r"\bI want to ask\b",
    r"\bCan you please\b",
    r"\bCould you please\b",
    r"\bWould you please\b",
    r"\bPlease help me\b",
    r"\bI need you to help me\b",
    r"\bI need help with\b",
]


redundant_patterns = [
    (r'\b(?:can|will|could|would|should|must)\s+you\s+(help|show|tell|explain|write|create|make|provide|give)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\byou\s+(?:need to|have to|are going to|are able to|are supposed to)\s+(help|show|tell|explain|write|create|make|provide|give)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\byou\s+are\s+capable\s+of\s+(helping|showing|telling|explaining|writing|creating|making|providing|giving)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\b(help|show|tell|teach|explain|describe|write|send|give|provide)\s+(?:me|to me)\b(?!\s+(?:to|with|how|what|where|about|understand|figure))', r'\1'),
    (r'\bI\s+(?:want|need|would like|require|ask|request)\s+(?:you\s+)?to\s+(?!\s+(?:know|understand|see|remember))', ''),
    (r'\bplease\s+(help|show|tell|explain|write|create|make|provide|give)\b(?!\s+(?:me\s+)?(?:to|with|how|what|why|this|that|a|an|some))', r'\1'),
    (r'\bI\s+need\s+(?:help|assistance|support)\b(?!\s+(?:with|to|understanding))', 'help'),
    (r'\bI\s+need\s+you\b(?!\s+(?:to|for|with))', ''),
    (r'\b(?:do|did|will|would)\s+you\b(?=\s+(?:have|know|think|understand|see|want|need|like))', ''),
    (r'\byou\s+(?:can\s+|will\s+|should\s+|must\s+|need to\s+|have to\s+)?do\s+this\b(?!\s+(?:by|with|for|to|when|where))', 'do this'),
]

greetings = {
    "hello", "hi", "hey", "greetings", "good morning", "good afternoon",
    "good evening", "dear", "to whom it may concern", "hi there",
    "hello there", "hey there", "good day", "howdy", "yo", "sup",
    "hiya", "g'day", "morning", "afternoon", "evening", "salutations",
    "welcome", "dearest", "how are you", "how are you doing",
    "what's up", "wassup", "how's it going", "hey folks", "hi folks"
}


request_patterns = [
    (r'\b(?:please\s+)?(help|assist|aid|support|explain|clarify|provide|give|show|demonstrate)\b', r'\1'),
    (r'\b(?:i would like|i want|i need|could you|can you|would you|please)\s+(?:to\s+)?(help|assist|aid|support|explain|clarify|provide|give|show|demonstrate)\b', r'\1'),
    (r'\b(?:could you help me with|can you help me with|would you help me with|please help me with|help me with|i need help with|i need you to help me with)\b', 'help with'),
    (r'\b(?:i would like to ask you to please|i would like to ask you to|i would like to ask|i want to ask you to|i want to ask|i am asking you to|i am requesting|i request that you|please)\b', ''),
    (r'\b(?:if you could|if you would|if possible|would you mind|would you kindly|could you please)\b', ''),
    (r'\b(?:thank you|thanks|much appreciated|many thanks|thanks a lot|thank you very much)\b', ''),
    (r'\bI\s+was\s+wondering\s*(?:if|whether)?\s*', ''),
    (r'\b(?:I\s+am|I\'m)\s+looking\s+(?:for|to)\s*', ''),
    (r'\b(?:I\s+would\s+like|I\'d\s+like)\s+to\s+(?:know|find\s+out|understand)\b\s*', ''),
    (r'\b(?:my|the)\s+question(?:\s+I\s+have)?\s+is\s*', ''),
    (r'\b(?:Can|Could|Would)\s+you\s+(?:tell\s+me|explain|show\s+me|provide\s+me\s+with)\b\s*', ''),
    (r'\b(?:I\s+am|I\'m)\s+(?:writing|contacting)\s+(?:you\s+)?to\s*', ''),
    (r'\b(?:I\s+need|I\s+want)\s+you\s+to\s*', ''),
    (r'\b(?:I\s+am|I\'m)\s+trying\s+to\s*', ''),

]

greeting_patterns = [
    r'^to\s+whom\s+it\s+may\s+concern[.!]?\s*',
    r'^good\s+(morning|afternoon|evening|day)[.!]?\s*',
    r'^dear\s+.*?,?\s*',
    r'\bhello there[.!]?\s*',
    r'\bhi there[.!]?\s*',
    r'\bhey there[.!]?\s*',
    r'\bhow are you( doing)?[.!]?\s*',
    r'\bwhat\'?s up[.!]?\s*',
    r'\bhey folks[.!]?\s*',
    r'\bhi folks[.!]?\s*',
    r'\bwelcome[.!]?\s*',
    r'\bsalutations[.!]?\s*',
    r'^hello[.!]?\s*',
    r'^hi[.!]?\s*',
    r'^hey[.!]?\s*',
    r'^howdy[.!]?\s*',
    r'^hiya[.!]?\s*',
    r'^g\'day[.!]?\s*',
    r'^yo[.!]?\s*',
    r'^sup[.!]?\s*',
]

chb_action_patterns = [
    r'\*([^*]+)\*',
    r'_([^_]+)_',
    r'\(([^)]+)\)',
    r'\[([^\]]+)\]'
]
chb_character_indicators = [
    r'\b(?:always|never|tends to|usually|often|sometimes|rarely)\s+\w+',
    r'\b(?:my|his|her|their)\s+(?:usual|typical|characteristic|signature)\s+\w+',
    r'\b(?:as usual|as always|like always|typically|characteristically)\b',
    r'\b(?:known for|prone to|has a habit of)\s+(?:[a-zA-Z]+ing|a\s+[a-zA-Z]+)',
    r'\b(?:a natural|an inherent)\s+(?:[a-zA-Z]+)',
]

chb_preserve = {
    'like', 'you know', 'I mean', 'well', 'so', 'then', 'now', 'just', 'actually', 'literally',
    'really', 'anyway', 'okay', 'alright', 'umm', 'uhh', 'hmm', 'oh', 'ah', 'oops',
    'pretty', 'quite', 'somewhat', 'rather',
    'of course', 'definitely', 'absolutely', 'certainly', 'truly', 'honestly', 'frankly',
    'in fact', 'as a matter of fact', 'to be honest', 'to tell you the truth',
    'you see', 'you know what I mean', 'what I\'m saying is',
    'all in all', 'at the end of the day', 'by and large', 'for the most part', 'in general', 'on the whole',
    'when it comes to', 'with respect to', 'with regard to',
    'the thing is', 'the point is', 'the fact of the matter is',
    "it's like", "it's kind of like", "is it possible that",
    "on the one hand",
    "by the way", "as it turns out"
}
chb_preserve_2 = {
    'please', 'thank you', 'thanks', 'sorry', 'excuse me', 'pardon me', 'apologies', 'my bad',
    'no worries', 'if you don\'t mind', 'would you kindly', 'could you please', 'I would appreciate it if'
}


chb_rp_patterns = [
    (r'\bhe/she\b', 'they'),
    (r'\bhis/her\b', 'their'),
    (r'\bhim/her\b', 'them'),

    (r'(?i)\b(?:I think|I believe|I guess|I suppose)\s+(?:that\s+)?(?=\w+\s+(?:is|are|was|were|will|would|can|could|should|might))', ''),
    (r'(?i)\b(?:maybe|perhaps|possibly|probably)\s+(?=\w+\s+(?:is|are|was|were|will|would))', ''),
    (r'(?i)\s*\b(?:as (?:you can see|mentioned|stated|noted))\s*,?\s*', ' '),
    (r'(?i)\s*\b(?:it is important to note that|it should be noted that|needless to say|as everyone knows)\b\s*', ' '), # Eat spaces
    (r'(?i)\s*\b(?:the fact that|as a matter of fact)\b\s*', ' '),
    (r'(?i)\s*\b(?:it is clear that|it goes without saying that)\b\s*', ' '),
    (r'(?i)\s*\b(?:at this point in time|at the present time)\b(?!\s+in\s+the\s+story)\s*', ' '),
    (r'(?i)\s*\b(?:in the near future)\b(?!\s+of\s+the\s+story)\s*', ' '),

    (r'\bif it is possible\b', 'if possible'),
    (r'\bwhen it is\b', 'when'),
    (r'\bwhere it is\b', 'where'),
    (r'\bwould seem to\b', 'seems to'),
    (r'\bappears to be\b', 'appears'),
    (r'\bseems to be\b', 'seems'),
    (r'\bthat is to say\b', 'meaning'),
    (r'\bin a way that\b', 'so'),
    (r'\bfor the purpose of\b', 'to'),
    (r'\bin the process of\s+([a-zA-Z]+ing)\b', r'\1'),
    (r'\bgive consideration to\b', 'consider'),
    (r'\bhas the ability to\b', 'can'),
    (r'\bis able to\b', 'can'),
    (r'\bmake a decision\b', 'decide'),
    (r'\bget rid of\b', 'remove'),
    (r'\btake into consideration\b', 'consider'),
    (r'\bis comprised of\b', 'comprises'),
    (r'\bwith the exception of\b', 'except'),
    (r'\bdue to the fact that\b', 'because'),
    (r'\bin spite of the fact that\b', 'although'),
    (r'\bin view of the fact that\b', 'since'),
    (r'\bas a consequence of\b', 'because of'),
    (r'\ba large number of\b', 'many'),
    (r'\ba small number of\b', 'few'),
    (r'\ba majority of\b', 'most'),
    (r'\bin the majority of cases\b', 'mostly'),
    (r'\bnotwithstanding the fact that\b', 'despite'),
    (r'\bprovided that\b', 'if'),
    (r'\bwith the result that\b', 'so that'),
    (r'\buntil such time as\b', 'until'),
    (r'\bin a timely manner\b', 'promptly'),
    (r'\bcome to a conclusion\b', 'conclude'),
    (r'\bput an end to\b', 'end'),
    (r'\bfind a solution to\b', 'solve'),
    (r'\btake part in\b', 'participate'),
    (r'\bdo away with\b', 'abolish'),
    (r'\bbring about\b', 'cause'),
    (r'\bpoint out\b', 'note'),
    (r'\bset forth\b', 'propose'),
    (r'\bcome across\b', 'find'),
    (r'\bgo through\b', 'experience'),
    (r'\btake up\b', 'begin'),
    (r'\bmake use of\b', 'use'),
    (r'\bget together\b', 'meet'),
    (r'\bput up with\b', 'tolerate'),
    (r'\blook into\b', 'investigate'),
    (r'\bcome up with\b', 'devise'),
    (r'\bgive rise to\b', 'cause'),
    (r'\bfor the most part\b', 'mostly'),
    (r'\bin the long run\b', 'eventually'),
    (r'\bin the short run\b', 'soon'),
    (r'\bas of now\b', 'now'),
    (r'\bin this day and age\b', 'today'),
    (r'\bby virtue of\b', 'because of'),
    (r'\bhave a tendency to\b', 'tend to'),
    (r'\bmake an effort to\b', 'try to'),
    (r'\bin the event of\b', 'if'),
    (r'\bwith reference to\b', 'regarding'),
    (r'\bfeel free to\b', 'feel free'),
    (r'\bin the normal course of events\b', 'normally'),
    (r'\bon a regular basis\b', 'regularly'),
    (r'\bfor all intents and purposes\b', 'practically'),
    (r'\bin a nutshell\b', 'briefly'),
    (r'\bto make a long story short\b', 'briefly'),
    (r'\bit would appear that\b', 'it appears that'),
    (r'\bit would seem that\b', 'it seems that'),
    (r'\bvery (?:very|much|greatly|highly|extremely)\b', 'very'),
    (r'\bextremely (?:very|much|greatly|highly)\b', 'extremely'),
    (r'\s*\b(?:as it happens|if you will|the fact of the matter is)\b\s*', ' '),
]

chatbot_optimizations = {
    "contractions": {
        "I am": "I'm", "you are": "you're", "he is": "he's", "she is": "she's",
        "it is": "it's", "we are": "we're", "they are": "they're", "I have": "I've",
        "you have": "you've", "we have": "we've", "they have": "they've", "would not": "wouldn't",
        "should not": "shouldn't", "could not": "couldn't", "do not": "don't",
        "does not": "doesn't", "did not": "didn't", "is not": "isn't",
        "are not": "aren't", "was not": "wasn't", "were not": "weren't",
        "will not": "won't", "cannot": "can't", "must not": "mustn't",
        "might not": "mightn't",
    },

    "preposition_simplifications": {
        "in order to": "to", "with regard to": "regarding", "in addition to": "also",
        "due to the fact that": "because", "on account of": "because", "by means of": "by",
        "with the exception of": "except", "prior to": "before", "subsequent to": "after",
        "for the purpose of": "to", "in the event that": "if",
    },

    "redundant_phrases": {
        "at this point in time": "now",
        "at the present time": "now",
        "in the near future": "soon",
        "in any case": "anyway",
        "first and foremost": "first",
        "last but not least": "finally",
        "new innovation": "innovation",
        "past history": "history",
        "future plans": "plans",
        "completely eliminate": "eliminate",
        "absolutely essential": "essential",
        "end result": "result",
        "final outcome": "outcome",
        "personal opinion": "opinion",
        "true facts": "facts",
        "joint collaboration": "collaboration",
        "each and every": "each",
        "over and above": "in addition",
        "various different": "various",
        "ultimate goal": "goal",
        "basic fundamentals": "fundamentals",
        "sudden impulse": "impulse",
        "temporary reprieve": "reprieve",
        "unexpected surprise": "surprise",
        "estimated guess": "guess",
        "actual fact": "fact",
        "connect together": "connect",
        "sum total": "total",
        "mutual cooperation": "cooperation",
        "exact replica": "replica",
        "free gift": "gift",
        "foreign imports": "imports",
        "safe haven": "haven",
        "return back": "return",
        "repeat again": "repeat",
        "sufficient enough": "sufficient",
        "personal feelings": "feelings",
    },

    "intensifier_reductions": {
        "very very": "very",
        "extremely very": "extremely",
        "really really": "really",
        "so very": "very",
        "too much": "much",
        "quite a bit": "a lot",
        "very much so": "very much",
        "absolutely completely": "completely",
        "totally entirely": "entirely",
    },

    "conjunction_simplifications": {
        "in addition to which": "and", "and also": "and", "but however": "but",
        "or alternatively": "or", "consequently and as a result": "consequently",
        "nevertheless and yet": "nevertheless", "as well as": "and",
    },

    "question_simplifications": {
        "I was wondering if you could tell me": "Can you tell me",
        "Do you happen to know": "Do you know",
        "Is it possible that": "Is it",
        "Could you possibly": "Could you",
        "Would it be alright if": "May I",
        "Do you think it would be a good idea to": "Should we",
    },

    "transition_simplifications": {
        "having said that": "however",
        "in conclusion": "finally",
        "to summarize": "in short",
        "first of all": "first",
        "last of all": "finally",
        "as a result": "so",
        "for this reason": "so",
        "in the meantime": "meanwhile",
        "to that end": "so",
    },

    "removable_fillers": [
        "umm", "uhh", "hmm", "uhm", "ummm", "uhhh", "uhmm",
    ],

    "courtesy_removals": [
        "please", "thank you", "thanks", "sorry", "excuse me", "pardon me", "apologies",
        "if you don't mind", "would you kindly", "could you please", "I would appreciate it if"
    ]
}